### ISSUE TITLE
classname check on sendMetrics and sendEvents is incorrect

### ISSUE THREAD

**Issue by aleonardMoogsoft** [Moogsoft/mars-sdk#28]
in index.js there is a check for constructor.name which is failing

`if (m.constructor.name !== 'Metric') {`

This should be changed to something like 

`if (m.constructor === Metric){`

Noted here https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/269

**Comment by MitchLillie** [comment]
Related to internal bug: https://moogsoft.atlassian.net/browse/MCP-6679

**Comment by MitchLillie** [comment]
Fixed in https://github.com/Moogsoft/mars-sdk/pull/29
